### PR TITLE
Adding docker with python2, cuda8

### PR DESCRIPTION
**Pull request by fninaparavecino**
Adding a docker that will solve the dependencies issues. It is working with --runtime=nvidia docker to access GPU. You will need cudnn and weights of the network in a docker_files folder

### CODE REVIEW

**Comment by rohitgirdhar** [comment]
Thanks @fninaparavecino! Could you please add a couple lines to the README with some instructions on how to use it?

**Comment by ajay-Bhammar** [comment]
@fninaparavecino  How to use this docker file ?

**Comment by fninaparavecino** [comment]
@rohitgirdhar you can build the docker with
$ docker build -t action:latest .

There is the need to have docker_files folder where there should be the cudnn5.1 (include and lib) and also the models folder.

**Comment by ajay-Bhammar** [comment]
> @rohitgirdhar you can build the docker with
> $ docker build -t action:latest .
> 
> There is the need to have docker_files folder where there should be the cudnn5.1 (include and lib) and also the models folder.

I have built docker successfully. Can you tell next instruction(like how to run docker image etc.) ? because when I run python file it showing some python libraries missing which is docker image. I am new to docker. Am I doing something wrong?

**Comment by fninaparavecino** [comment]
@ajay-Bhammar to run docker image use the next line:
$ docker run -it --runtime=nvidia action:latest
The Dockerfile is running with nvidia docker so it can use the GPU. Once within the docker you have to run the regular way for the demo of ActionVLAD the code should be in the /app folder

**Comment by ajay-Bhammar** [comment]
> @ajay-Bhammar to run docker image use the next line:
> $ docker run -it --runtime=nvidia action:latest
> The Dockerfile is running with nvidia docker so it can use the GPU. Once within the docker you have to run the regular way for the demo of ActionVLAD the code should be in the /app folder

Thanks for help

**Pull request merged**
